spring.application.name=API-Entregas
server.port=8181

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:entregadb
spring.datasource.username=sa
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.password=
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=688c5ca254cdf622f05344c045a0c52d3decd4b77298b2e144cdea4ac36bd8da
jwt.expiration=3600000